### ISSUE TITLE
Remove Unused Settings Option

### ISSUE THREAD

**Issue by joshuaskelly** [joshuaskelly/vscode-quakec#13]
# Summary
We inherited `quakec.maxNumberOfProblems` from the LSP sample project. We should either use it, or remove it.

**Comment by Paril** [comment]
Which branch do we do this in? Might as well just remove it. It's main use is for languages like C/C++ where you might have a project with like a thousand files. It'll never be a problem with QC.

**Comment by joshuaskelly** [comment]
Here you go: #14
